// ============================================================
// /api/r/[token]
//
// GET → returns the cached report HTML for a shared snapshot.
//
// No auth. Token is the auth — anyone with it can read the report.
// Token is generated by the share toggle endpoint and stored on
// discovery_score_snapshots.share_token.
//
// Returns the same report_html that the owner sees in their
// dashboard. Includes minimal metadata (site domain, snapshot date)
// for header rendering on the public page.
// ============================================================

import { NextRequest, NextResponse } from 'next/server';
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import { looksLikeShareToken } from '@/lib/shareTokens';

export const maxDuration = 10;

function getAdminClient(): SupabaseClient {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
  );
}

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ token: string }> },
): Promise<NextResponse> {
  const { token } = await params;

  if (!looksLikeShareToken(token)) {
    return NextResponse.json({ error: 'Not found' }, { status: 404 });
  }

  const admin = getAdminClient();

  const { data: snapshot, error } = await admin
    .from('discovery_score_snapshots')
    .select('id, site_id, snapshot_date, report_html, report_generated_at, sites(domain)')
    .eq('share_token', token)
    .maybeSingle();

  if (error || !snapshot || !snapshot.report_html) {
    return NextResponse.json({ error: 'Not found' }, { status: 404 });
  }

  // The sites join shape varies depending on Supabase client version;
  // handle either single-object or array form
  const site = Array.isArray(snapshot.sites) ? snapshot.sites[0] : snapshot.sites;
  const domain = ((site as { domain?: string } | null)?.domain as string) || '';

  return NextResponse.json({
    html: snapshot.report_html,
    domain,
    snapshot_date: snapshot.snapshot_date,
    report_generated_at: snapshot.report_generated_at,
  });
}
