// ============================================================
// /robots.txt — generated by Next.js metadata route.
//
// AIVA tells customers to make their sites legible to AI
// crawlers. This file makes sure AIVA itself does the same
// ("we pass our own scan"). AI agents are *explicitly* named
// and allowed on public marketing pages; private surfaces
// (dashboard, API, auth, tokenized share links) are disallowed
// for everyone.
//
// Keep the AI_AGENTS list loosely in sync with the list the
// scanner checks in src/lib/scanner.ts.
// ============================================================

import type { MetadataRoute } from 'next';

const BASE_URL = process.env.NEXT_PUBLIC_APP_URL || 'https://aivascan.com';

// Private / non-marketing surfaces. Share links (/r/...) are
// excluded so tokenized customer reports never end up indexed.
const DISALLOWED = [
  '/api/',
  '/dashboard/',
  '/auth/',
  '/audit/',
  '/site/',
  '/r/',
  '/checkout/',
];

// AI assistant + AI search crawlers we explicitly welcome on
// public pages. A plain "*" rule already covers them, but naming
// them is deliberate: it signals intent and mirrors the advice
// AIVA gives its own customers.
const AI_AGENTS = [
  'GPTBot',
  'ChatGPT-User',
  'OAI-SearchBot',
  'ClaudeBot',
  'Claude-User',
  'Claude-SearchBot',
  'anthropic-ai',
  'PerplexityBot',
  'Perplexity-User',
  'Google-Extended',
  'Amazonbot',
  'Applebot-Extended',
  'meta-externalagent',
  'CCBot',
  'cohere-ai',
];

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      // Everyone (including search engines): public pages yes,
      // private surfaces no.
      { userAgent: '*', allow: '/', disallow: DISALLOWED },
      // Explicit allow for AI crawlers on the same terms.
      ...AI_AGENTS.map((agent) => ({
        userAgent: agent,
        allow: '/',
        disallow: DISALLOWED,
      })),
    ],
    sitemap: `${BASE_URL}/sitemap.xml`,
  };
}
